[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
verifire_product = "6a6EMSNxCrFzcLA38Q5WwcPWgyDPqdghaoaWhvHAEnj8"

[programs.localnet]
verifire_product = "6a6EMSNxCrFzcLA38Q5WwcPWgyDPqdghaoaWhvHAEnj8"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
